const GET_CURRENT = 'HOME/GET_CURRRENT';
const GET_FORCAST = 'HOME/GET_FORCAST';
const SET_PAGE = 'HOME/SET_PAGE';
const SHOW_WINDOW = 'HOME/SHOW_WINDOW';
const SELECT_CITY = 'HOME/SELECT_CITY';
export default { GET_CURRENT, GET_FORCAST, SET_PAGE, SHOW_WINDOW, SELECT_CITY };
